class Singleton {
    constructor() {
      
      this.tags = [
        "Artificial Intelligence",
        "Computer Science",
        "Data Science",
        "Web Development",
        "Software Engineering",
        "Computer Networking",
        "Database Systems",
        "Computer Graphics",
        "UX/UI Design",
        "Embedded Systems",
        "Cryptography",
        "Quantum Computing",
        "Blockchain",
        "Internet of Things",
        "Machine Learning",
        "Deep Learning",
        "Natural Language Processing",
        "Digital Marketing",
        "Cloud Computing",
        "Big Data",
        "Hadoop",
        "Spark",
        "AWS",
        "Azure",
        "GCP",
        "Docker",
        "Kubernetes",
        "Linux",
        "Git",
        "Python",
        "Java",
        "C++",
        "JavaScript",
        "PHP",
        "Ruby",
        "Swift",
        "Objective-C",
        "R",
        "MATLAB",
        "Scratch",
        "Excel",
        "Word",
        "PowerPoint",
        "Microsoft Access",
        "HTML",
        "CSS",
        "Angular",
        "React",
        "Vue",
        "Redux",
        "Flask",
        "Django",
        "Laravel",
        "Spring",
        "Hibernate",
        "TensorFlow",
        "Pandas",
        "NumPy",
        "Scikit-learn",
        "Jupyter Notebook",
        "OpenCV",
        "SOLID",
        "GRASP",
        "Singleton",
        "Observer",
        "Factory Method",
        "Prototype",
        "Bridge",
        "Composite",
        "Decorator",
        "Facade",
        "Flyweight",
        "Adapter",
        "Proxy",
        "Chain of Responsibility",
        "Command",
        "Interpreter",
        "Iterator",
        "Mediator",
        "Memento",
        "State",
        "Strategy",
        "Template Method",
        "Visitor",
        "LEAN Startup",
        "Agile Development",
        "Scrum",
        "Kanban",
        "Lean Software Development",
        "Spiral Model",
        "V Model",
        "Waterfall Model",
        "Software Requirements",
        "Software Architecture",
        "Software Design",
        "Software Testing",
        "Software Deployment",
        "Software Maintenance",
        "Software Evolution",
        "Software Process",
        "Software Engineering Models",
        "Software Quality",
        "Software Configuration Management",
        "Software Project Management",
        "Software Release Management",
        "Software Development Lifecycle",
        "Software Development Methodologies",
        "Software Development Processes",
        "Software Development Standards",
        "Software Development Tools",
        "Software Development Techniques",
        "Software Development Methodologies",
        "Software Development Paradigms",
        "Software Development Styles",
        "Software Development Trends",
        "Software Development Life Cycle Models",
        "Software Development Frameworks",
        "Software Development Methods",
        "Software Development Principles",
        "Software Development Theories",
        "Software Development Techniques",
        "Software Development Values",
        "Software Development Approaches",
        "Software Development Best Practices",
        "Software Development Methodologies",
        "Software Development Paradigms",
        "Software Development Patterns",
        "Software Development Practices",
        "Software Development Styles",
        "Software Development Trends",
        "Software Development Values",
        "Software Development Metrics",
        "Software Development Evaluation",
        "Software Development Estimation",
        "Software Development Budgeting",
        "Software Development Resource Management",
        "Software Development Human Resource Management",
        "Software Development Organizational Resource Management",
        "Software Development Team Building",
        "Software Development Talent Management",
        "Software Development Workforce Management",
        "Software Development Skill Management",
        "Software Development Learning and Development",
        "Software Development Employee Engagement",
        "Software Development Employee Satisfaction",
        "Software Development Performance Management",
        "Software Development Workflow Management",
        "Software Development Collaboration",
        "Software Development Participation",
        "Software Development Sharing",
        "Software Development Innovation",
        "Software Development Experimentation",
        "Software Development Discovery",
        "Software Development Risk Management",
        "Software Development Failure Analysis",
        "Software Development Root Cause Analysis",
        "Software Development Debugging",
        "Software Development Problem Solving",
        "Software Development Quality Assurance",
        "Software Development Code Review",
        "Software Development Test Driven Development",
        "Software Development Continuous Integration",
        "Software Development Continuous Deployment",
        "Software Development DevOps",
        "Software Development Technical Debt Management",
        "Software Development Tech Debt",
        "Software Development Systematic Debt Management",
        "Software Development Cost-Benefit Analysis",
        "Software Development Investment Analysis",
        "Software Development Payback Period",
        "Software Development Break-Even Point",
        "Software Development Cash Flow Management",
        "Software Development Capital Budgeting",
        "Software Development Zero-Based Budgeting",
        "Software Development Budget Allocation",
        "Software Development Budget Execution",
        "Software Development Budget Control",
        "Software Development Performance Measurement",
        "Software Development Benchmarking",
        "Software Development Metrics Analysis",
        "Software Development Business Intelligence",
        "Software Development Decision Making",
        "Software Development Forecasting",
        "Software Development Simulation",
        "Software Development Visualization",
        "Software Development Modeling",
        "Software Development Strategy",
        "Software Development Tactics",
        "Software Development Grand Strategy",
        "Software Development Mega Trends",
        "Software Development Gartner Hype Cycle",
        "Software Development Futures",
        "Software Development Emerging Technologies",
        "Software Development Future of Work",
        "Software Development Innovation Ecosystem",
        "Software Development Startup Ecosystem",
        "Software Development Accelerator Ecosystem",
        "Software Development Investor Ecosystem",
        "Software Development Tech Ecosystem",
        "Software Development Tech Stack",
        "Software Development Stack Overflow",
        "Software Development Stack Exchange",
        "Software Development Developer Ecosystem",
        "Software Development Research Ecosystem",
        "Software Development Academia Ecosystem",
        "Software Development Community Ecosystem",
        "Software Development Ecosystems",
        "Software Development Platform Ecosystems",
        "Software Development Ecosystem Evolution",
        "Software Development Ecosystem Development",
        "Software Development Ecosystem Dynamics",
        "Software Development Ecosystem Modeling",
        "Software Development Ecosystem Analysis",
        "Software Development Ecosystem Assessment",
        "Software Development Ecosystem Prediction",
        "Software Development Ecosystem Simulation",
        "Software Development Ecosystem Visualization",
        "Software Development Ecosystem Metrics",
        "Software Development Ecosystem Benchmarking",
        "Software Development Ecosystem Buzz",
        "Software Development Ecosystem Growth",
        "Software Development Ecosystem Health",
        "Software Development Ecosystem Management",
        "Software Development Ecosystem Strategy",
        "Software Development Ecosystem Tactics",
        "Software Development Ecosystem Innovation",
        "Software Development Ecosystem Participation"
    ];
      this.courses = [
        "Structured Programming (CSE014)",
        "Introduction to Engineering Physics (PHY212)",
        "Engineering Drawing (1) (MEC011)",
        "Mathematics I (MAT111)",
        "Mechanics (MAT123)",
        "Mathematics II (MAT112)",
        "Probability & Statistics I (MAT131)",
        "Object Oriented Programming (CSE015)",
        "Discrete Mathematics (CSE315)",
        "Linear Algebra (MAT212)",
        "Data Structures (CSE111)",
        "Electric & Electronic Circuits (CSE113)",
        "Logic Design (CSE131)",
        "Differential Equations (MAT312)",
        "Computer Architecture & Organization (CSE132)",
        "Artificial Intelligence (AIE111)",
        "Engineering Chemistry (CHE142)",
        "Dynamics (MAT121)",
        "Statics (MAT122)",
        "Numerical Analysis (MAT315)",
        "Physics II (PHY211)",
        "Database Systems (MAT221)",
        "Operating Systems (CSE221)",
        "Machine Learning (AIE121)",
        "Electrical Circuits & Measurements (ELE115)",
        "Electronics & Digital Circuits (ELE215)",
        "Fundamentals of Communication Systems (ELE232)",
        "Automatic Control Systems (ELE233)",
        "Wireless Communication Networks (ELE338)",
        "Design & Analysis of Algorithms (CSE112)",
        "Web Programming (CSE122)",
        "Software Engineering (CSE251)",
        "Computer Networks (CSE261)",
        "Embedded Systems (CSE234)",
        "Image Processing (CSE281)",
        "Digital Signal Processing (ELE432)",
        "Security of Information Systems (CSE241)",
        "Cryptography (CSE242)",
        "Cloud Computing (CSE363)",
        "Introduction to Cyber Security (CSE344)",
        "Secure Programming (CSE243)",
        "Parallel Programming (CSE373)",
        "Information & Computer Networks Security (CSE446)",
        "Internet of things (CSE392)",
        "Computer Vision (CSE383)",
        "Knowledge-Based Systems (AIE212)",
        "Optimization Techniques (AIE213)",
        "Neural Networks (AIE231)",
        "Selected Topics in Information Security (CSE445)",
        "Graduation Project 1 (CSE493)",
        "Selected Topics in Computer Security (CSE447)",
        "Graduation Project 2 (CSE494)",
        "Robotics Design (AIE351)",
        "Graduation Project 1 (CSE493)",
        "Deep Learning (AIE332)",
        "Graduation Project 2 (CSE494)"
      ];
    }
  
 
    getTags() {
      return this.tags;
    }
  
    getCourses() {
      return this.courses;
    }
  
    
    static getInstance() {
      if (!Singleton.instance) {
        Singleton.instance = new Singleton();
      }
      return Singleton.instance;
    }
  }
  
  
  const singletonInstance = Singleton.getInstance();
  
  
  const tags = singletonInstance.getTags();
  const courses = singletonInstance.getCourses();
  
  export default Singleton;